# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &${ORG_NAME}
    # DefaultOrg defines the organization which is used in the sampleconfig
    # of the fabric.git development environment
    Name: ${ORG_MSPID}

    # ID to load the MSP definition as
    ID: ${ORG_MSPID}

    MSPDir: crypto-config/peerOrganizations/${ORG_DOMAIN}/msp

    # Policies defines the set of policies at this level of the config tree
    # For organization policies, their canonical path is usually
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('${ORG_MSPID}.admin', '${ORG_MSPID}.peer', '${ORG_MSPID}.client')"
      Writers:
        Type: Signature
        Rule: "OR('${ORG_MSPID}.admin', '${ORG_MSPID}.client')"
      Admins:
        Type: Signature
        Rule: "OR('${ORG_MSPID}.admin')"

    AnchorPeers:
      # AnchorPeers defines the location of peers which can be used
      # for cross org gossip communication.  Note, this value is only
      # encoded in the genesis block in the Application section context
      - Host: peer0.${ORG_DOMAIN}
        Port: ${PORT}
